### ISSUE TITLE
Only returns 10 entries for skills, abilities, etc.

### ISSUE THREAD

**Issue by tyleransom** [eknud/ONETr#1]
First off, this package is amazing! Thank you for developing it.

I am using it, and noticing that only the top 10 skills or knowledge or abilities entries are included. For example, if I visit the [summary report for Clinical Psychologists](https://www.onetonline.org/link/summary/19-3031.02), it lists 19 skills and 16 abilities. But when I use the package to download through the API, I only get the top 10 of each.

Is this a limitation of the API? Do you know how to get the entire list for each entry?

**Comment by eknud** [comment]
This has been addressed -- the default behavior of socSearch is now to return all results. The burden of subsetting this data to a preferred list is now pushed to the user. Hope this helps!

**Comment by tyleransom** [comment]
I'm seeing some odd behavior from the development version of the package. Here is the code I am running:


```r
library(tidyverse)
library(magrittr)
library(ONETr)

output <- jobSearch("19-3031.02",type="soc")

output.kn <- jobInfo(output,"k") %>% as_tibble

output.kn %>% print

  .id   href  title.text title..attrs.id example example.text example..attrs.…
  <chr> <fct> <fct>      <fct>           <fct>   <fct>        <fct>           
1 see_… http… NA         NA              NA      NA           NA              
2 cate… NA    Medical s… 43232610        UNI/CA… Healthcare … 105             
3 cate… NA    Analytica… 43232605        Testin… NA           NA              
4 cate… NA    Spreadshe… 43232110        NA      Microsoft E… 1               
5 cate… NA    Accountin… 43231601        MPMsof… NA           NA              
6 cate… NA    Office su… 43231513        NA      Microsoft O… 147             
7 cate… NA    Word proc… 43232104        NA      Microsoft W… 143             
8 cate… NA    Internet … 43232705        Web br… NA           NA              
9 cate… NA    Calendar … 43232108        Spectr… NA           NA              
# … with 1 more variable: .attrs.related <fct>
```
which looks a lot like the technology skills and not the knowledge categories. (Plus, if I use it to get knowledge or abilities, I don't see any of the numerical 0-100 scores for each element.)

I get this same issue if I run it on the previous commit (`6f135f3`).

If I go back to the commit before that (which I think is the current CRAN version), then I get the following (using the old syntax):
```r
output <- socSearch("19-3031.02")

output.kn <- knowledge(output) %>% as_tibble

output.kn %>% print
# A tibble: 10 x 8
   .id   name  description score.text score..attrs.sc… score..attrs.im…
   <chr> <fct> <fct>       <fct>      <fct>            <fct>           
 1 elem… Psyc… Knowledge … 100        Importance       true            
 2 elem… Ther… Knowledge … 98         Importance       true            
 3 elem… Engl… Knowledge … 88         Importance       true            
 4 elem… Cust… Knowledge … 74         Importance       true            
 5 elem… Law … Knowledge … 54         Importance       true            
 6 elem… Admi… Knowledge … 52         Importance       true            
 7 elem… Educ… Knowledge … 50         Importance       true            
 8 elem… Publ… Knowledge … 50         Importance       true            
 9 elem… Phil… Knowledge … 48         Importance       false           
10 elem… Medi… Knowledge … 46         Importance       false           
# … with 2 more variables: .attrs.id <fct>, .attrs.related <fct>
```
which is as I expected (except for the truncation at 10). 

I may fork this and see if I can't figure out what's going on. In any case, I find this package insanely helpful and am logging this issue mostly to make the developers aware and not to complain. 😃

**Comment by eknud** [comment]
Thanks for the heads up! This is almost certainly a result of the (untested) update. Let me poke around and get back to you! I have sense of what's going on.

**Comment by tyleransom** [comment]
FYI I forked it and made the change you had made most recently (add `?display=long` to the `getURL()` call), and everything is working as I would hope when I first opened this issue.

Thanks for being responsive! I would be happy to test the new update when you've had a chance to patch the error I noticed a few days ago.

**Comment by eknud** [comment]
@tyleransom So to clarify before I dive in, the issue from 19-20 days ago is resolved, but not the issue from 3 days ago, correct?

**Comment by eknud** [comment]
@tyleransom I believe I've fixed the second issue. A lookup key was incorrectly stored as a factor, and being converted to numeric when being used as an index. This key is now explicitly converted to character as soon as it is looked up. I have tested this and it appears to be working (closing the issue for now).
